name: streamdata
version: 0.1.0.0
github: 'githubuser/streamdata'
license: BSD3
author: 'Author name here'
maintainer: 'example@example.com'
copyright: '2019 Author name here'

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/streamdata#readme>

# NOTE, the latest version of streamly is 0.7.0+
dependencies:
  - base >= 4.7 && < 5
  - conduit == 1.3.1.1
  - streamly == 0.6.1
  - pipes == 4.3.13
  - mtl == 2.2.2
  - path-io == 1.4.2
  - path == 0.6.1

library:
  source-dirs: src

executables:
  streamly:
    main: Main.hs
    source-dirs: app/streamly
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - streamdata
  pipeline:
    main: Main.hs
    source-dirs: app/pipeline
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - streamdata
tests:
  streamdata-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - streamdata
